### ISSUE TITLE
Toolbar improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#1]
- Save, Load buttons on the left toolbar panel should have similar look & feel (white background) as others on this panel. In general, these buttons should not be very high and should not be very wide. Paddings around these buttons should also be decreased for a "compact" arrangement of the toolbar.

- Width of the left toolbar panel is currently varying. When the window is small, it occupies the entire window. When you increase it, initially it's reasonable but button icons don't fit the button! Then if you further increase it, then it gets too wide. Why not keep it at a fixed width?

- Interactions should also have icons associated. In this case I suppose Legends are not meaningful (could be removed).

**Comment by istemi-bahceci** [comment]
Fixed first and third, but second one is still a bit problematic.

**Comment by ugurdogrusoz** [comment]
2nd issue looks good to me? The only thing is I would:
- decrease the width of the buttons on the toolbar (by 25% or so)
- decrease the padding around the buttons (margins on all for sides)
to produce a more "compact" toolbar.
