### ISSUE TITLE
File and pathway name

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#15]
The user should be able to give the name a pathway, which is also used as file name. This could be displayed on the menu bar (between menu items and the tool name, in the middle). It should be a text field, modifiable by the user (on double click?).

**Comment by istemi-bahceci** [comment]
fixed.

**Comment by ugurdogrusoz** [comment]
This is great but I am not sure about its location for two reasons:
- further lowers the drawing canvas
- double-click to change moves the canvas
How about putting it under "File" in the toolbar (before Load and Save)?
Btw, we should change "Load" to "Load..."

**Comment by istemi-bahceci** [comment]
This should be fixed now.

**Comment by ugurdogrusoz** [comment]
Can we somehow have enough padding around the filename text so that when you click on the file name to change it, the buttons below do not shift?
