### ISSUE TITLE
Specialized layout

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#16]
A specialized layout might come in handy for these types of pathways:
- some way to keep disconnected nodes of a family of genes together,
- some way to constrain any compartments so that their adjacencies are as desired,
- anything to do with the flow?
Let's discuss this when you get a chance.

**Comment by ugurdogrusoz** [comment]
Let's do the following only for now:
To keep disconnected nodes of a family closer within the compound:
- before layout begins, created 1 dummy CoSENode with minimal dimensions (w=1,h=1) and 1 dummy CoSEEdge per family member gene connected from this member gene to the dummy node.
- after layout finishes, get rid of the created dummy node and its incident dummy edges.

**Comment by ugurdogrusoz** [comment]
I suggest we implement this within cose-bilkent for all compounds. In other words, if a compound node's children are all degree zero within the compound (might have inter-graph edges going outside the compound but no two children of the compound are connected), we can choose to add a dummy node before layout begins that connects to all children, to hold them together, and get destroyed after layout finishes.

**Comment by ugurdogrusoz** [comment]
Let's please use the latest release of cose-bilkent layout and change the following option(s):
- gravityRange 3.8 -> 1.5

**Comment by ugurdogrusoz** [comment]
Btw, this new feature (keeping disconnected nodes of a compound together with a dummy node) should directly go into cose-bilkent!

**Comment by istemi-bahceci** [comment]
Fixed, I will move changes to the cose-bilkent as well. But I suggest keeping local cose-bilkent copy a bit more since it is handy for experimenting internal layout changes.

**Comment by ugurdogrusoz** [comment]
Sure, let's keep it local for now. Please move this change to cose-bilkent now though.

**Comment by ugurdogrusoz** [comment]
Let's not transfer these changes to cose-bilkent for now.
