### ISSUE TITLE
Alignment operations

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#18]
Let's implement operations (similar to those in SBGNViz) for aligning nodes w.r.t. top, bottom, left, right or centers of nodes. Let's first talk about user interface.

**Comment by ugurdogrusoz** [comment]
Can we please make sure the alignment is done w.r.t. to the first selected node?

**Comment by istemi-bahceci** [comment]
Should be fixed now
