### ISSUE TITLE
About

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#2]
Page title & title of menu bar: "TCGA Curation Tool" -> "TCGA Pathway Curation Tool"

Help > About:
- After title (About) and before ivis logo, we should write "TCGA Pathway Curation Tool"
- Update URL
- Decrease window width

About TCGA Curation Tool (bottom of window):
- "About TCGA Curation Tool" -> "About TCGA Pathway Curation Tool"
- Text: This is a curation tool for TCGA pan-cancer pathway people to help them prepare the topology and layout of these pathways using a uniform notation.

**Comment by ugurdogrusoz** [comment]
Very nice! Nice choice of color as well. Need to fix the sentence as follows though: ".. people for preparing the topology and layout of these pathways using a uniform notation."

**Comment by istemi-bahceci** [comment]
Fixed.

**Comment by ugurdogrusoz** [comment]
Could we change the font color for email and URL to the dark blue we now use in the menu background, etc. for consistency please?
