### ISSUE TITLE
Disable node details when in interaction creation mode

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#22]
We should disable node details when in interaction creation mode, since it often blocks the user's view.

**Comment by ugurdogrusoz** [comment]
We might want to display node details only when the node is selected! Otherwise they pop everywhere (even though we have some delay) and mess things up during editing.

**Comment by istemi-bahceci** [comment]
I agree, changed behaviour now, node details are shown when direct click on node is performed.
