### ISSUE TITLE
Create a folder in Google Drive for application data in real time mode

### ISSUE THREAD

**Issue by istemi-bahceci** [iVis-at-Bilkent/TCGA-Curation-Tool#26]
We need to populate application data generated by curation tool into a folder in Google Drive, otherwise all newly created collaborative graphs goes to the root folder of the user's drive, which creates a mess.

**Comment by istemi-bahceci** [comment]
In real time created app specific graph files are now created under folder 'TCGA_Pathway_Curation_Tool_Files', If such folder does not exists tool creates a folder with name 'TCGA_Pathway_Curation_Tool_Files' and put all app generated graph files here.

**Comment by ugurdogrusoz** [comment]
i don't see such a folder created?

**Comment by istemi-bahceci** [comment]
Forgot to deploy to tcga.patika.org , Just deployed latest version.
