### ISSUE TITLE
Load and Merge is not working properly with compound graphs while using collaborative mode 

### ISSUE THREAD

**Issue by istemi-bahceci** [iVis-at-Bilkent/TCGA-Curation-Tool#28]
Due to real time API work flow, we should insert graph nodes according to the nesting level when using collaborative mode. E.g. First topmost nodes, then nodes that have nesting level of 1 .. etc.

**Comment by istemi-bahceci** [comment]
Fixed.

**Comment by ugurdogrusoz** [comment]
Here is a scenario with merge missing an interaction (all done in collaborative mode):
- create a pathway with genes G1, and G2, and family F (which contains) G1, and an activation edge from G2 to G1.
- save this pathway (pathway.txt)
- in a second window, start from scratch and create a new pathway with genes G1 and G3, and compartment C, with an inhibition edge from G3 to G1.
- merge with pathway.txt. I expect G1 to have 2 edges (one inhibition from G3 and one activation from G2) but I get only one inhibition edge (the activation edge is not merged!)

**Comment by istemi-bahceci** [comment]
Edge part is fixed but, what about node F ? Since it does not exist in the current pathway ( pathway with genes G3 and G1 ) a new family is created when merge is performed, but since G1 is child of C in current pathway and child of F in the merged one, what should we do about this case ? Now an empty family F is created when merge is performed.

**Comment by ugurdogrusoz** [comment]
I didn't describe the scenario correctly. In both pathways G1 should have been in Family F1. In case containment relations do not match (in one drawing G1 is in the root & in the other it's in a family) we can just clone them. In other words we create two G1's one in the root, the other in the family.
