### ISSUE TITLE
Menubar improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#3]
Change title "TCGA Pathway Curation Tool" (to the left of the menu items) color to blue.

File > New, Load ..., Save ... (not the 3 dots for operations with succeeding steps)
Layout > Perform Layout, Layout Properties ...
Help > Quick Help, About

Quick Help should open up a window (similar to About) with following content:
Title: Quick Help
Text:
    - To add a node: Drag and drop from node palette
    - To add an interaction: Click on interaction type; then click on source node and release on target node
    - To add a node into a container (family or compartment): Drag the node into its container node or select nodes to be contained and right click on container node and choose "Add Selected Into This Node"
    - To delete nodes/interactions: Select and perform Edit > Delete Selected

**Comment by ugurdogrusoz** [comment]
Nice; just missing File > New (creates a blank pathway).

**Comment by istemi-bahceci** [comment]
Added missing 'New' functionality and formatted quick help text.

**Comment by ugurdogrusoz** [comment]
Sorry, "Save" should not have "..." since it automatically saves without letting user choose location/name.

**Comment by istemi-bahceci** [comment]
removed '...' .
