### ISSUE TITLE
Layout not maintained on save/load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#31]
Looks like on load the layout of the pathway is somehow different (nodes are closer to each other than at the time they were on save?)

**Comment by istemi-bahceci** [comment]
I think it should be fixed now.

**Comment by istemi-bahceci** [comment]
Guess not :)

**Comment by istemi-bahceci** [comment]
Should be fixed by now.
