### ISSUE TITLE
Increase default node sizes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#32]
Try this:
width = 1.5 x width
height = 2 x height
Make sure the font size is adjusted accordingly.

**Comment by ugurdogrusoz** [comment]
Can we also decrease the font size of all the menu / toolbar items etc? They look too big (like the tool was designed for kids or elderly :)

**Comment by istemi-bahceci** [comment]
I think this should be ok now ?
