### ISSUE TITLE
Suggestions to rename some menu item names

### ISSUE THREAD

**Issue by schultzn** [iVis-at-Bilkent/TCGA-Curation-Tool#35]
1. Rename "File" menu --> "Network"
2. Rename "Data" --> "Alteration frequencies"
3. Rename "Save" --> "Export"

**Comment by ugurdogrusoz** [comment]
@schultzn Isn't "Alteration Frequencies" too long as a menu name? How about "Alteration Data" or just "Alteration"?

**Comment by schultzn** [comment]
I think "Alteration %" will work - what do you think?

**Comment by istemi-bahceci** [comment]
I think "Alteration %" is ok. Renamed associated items accordingly.
