### ISSUE TITLE
Drag node into a container node on creation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#5]
When a new node is dragged into a container node, it should be directly added into the container as a child node.
Regarding adding a node as a child into a container node, we have the following constraint though: a compartment can contain anything but a family can only contain another family or genes. So if a process or a compartment is transferred into a family, we should not do it and ignore it.

**Comment by istemi-bahceci** [comment]
fixed.
