### ISSUE TITLE
Selection hardly visible

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#6]
When nodes and/or interactions are selected, they are not marked well and they are hardly visible (esp. interactions)

**Comment by ugurdogrusoz** [comment]
Did you try the shade of purple I shared with you as selection color?

**Comment by istemi-bahceci** [comment]
![image](https://cloud.githubusercontent.com/assets/8645080/15689007/979be2b4-2785-11e6-9c80-538e0c45eaa7.png)

also increased interaction width to make them more visible when selected.
