### ISSUE TITLE
Entrez Gene properties through BioGene

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#8]
The inspector that currently displays only node labels should also provide a button named "EntrezGene details". When this button is pressed, corresponding gene information should be fetched from EntrezGene using the BioGene service, and list/append them to the end of the inspector.

**Comment by istemi-bahceci** [comment]
Added this feature.

**Comment by ugurdogrusoz** [comment]
Looks great!
