### ISSUE TITLE
Construct a default pathway

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/TCGA-Curation-Tool#9]
using one of the examples provided by Niki

**Comment by ugurdogrusoz** [comment]
Please use this pathway as default (on initial page load)

[RAS.txt](https://github.com/iVis-at-Bilkent/TCGA-Curation-Tool/files/294026/RAS.txt)

**Comment by istemi-bahceci** [comment]
Realized that there occurs a collision about element ids in cytoscape when we do not specify id for edges, fixed and updated the sample graph file.

[RAS.txt](https://github.com/iVis-at-Bilkent/TCGA-Curation-Tool/files/295230/RAS.txt)
